'save_dir': './../generated_data_v1'
'DIR': 'us_import1'
'train_data_file': 'train_data.csv'
'test_data_file': 'test_data.csv'
'id_col': 'PanjivaRecordID'
'num_jobs': 16
'hscode_col': 'HSCode'
'freq_bound_ABSOLUTE' : 25
'freq_bound_PERCENTILE' : 5

'us_import1':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 25

'us_import2':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 5

'us_import3':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 5

'us_import4':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 5

'us_import5':
  'use_cols':
    - PanjivaRecordID
    - ConsigneePanjivaID
    - ShipperPanjivaID
    - Carrier
    - ShipmentOrigin
    - ShipmentDestination
    - PortOfUnlading
    - PortOfLading
    - HSCode
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'low_freq_bound': 5